config/routes.rb
CloudCount2::Application.routes.draw do

  resources :audits

  resources :sessions, :only => [:new, :create, :destroy]
  match 'logout', to: 'sessions#destroy', as: :logout
  match 'login', to: 'sessions#new', as: :login

  resources :budgets do 

    resources :lines

    resources :notes

    resources :attachments

  end
  match '/budgets/:id/:category', to: 'budgets#show'

  match '/budgets/:budget_id/lines/new/:category', to: 'lines#new'
  resources :lines do
    resources :sublines
  end

  resources :sublines do
    resources :transactions
  end

  resources :users
  match 'signup', to: 'users#new', as: :signup

  root :to => 'budgets#index'

end

app/models/line.rb
class Line < ActiveRecord::Base
    attr_accessible :category, :budget_id, :line_number, :name, :subtotal, :order

    CATEGORIES = ['incomes', 'expenses']

    belongs_to :budget

    has_many :sublines, :dependent => :destroy

    audited

    def budget_total
        if @budget_total.nil?
            @budget_total = self.sublines.reduce(0) do |sum, subline|
                sum + subline.subtotal
            end
        end
        @budget_total
    end

    def actual
        if @actual_total.nil?
            @actual_total = self.sublines.reduce(0) do |sum, subline|
                sum + subline.actual
            end
        end
        @actual_total
    end

    def excess
        self.budget_total - self.actual
    end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  
  respond_to :html, :json

  before_filter :setup
  before_filter :require_login

  def setup
    @subtitle = 'Lines'
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
    @line = Line.includes({:sublines => :transactions}).find(params[:id])
    @budget = @line.budget
    @subtitle = '%s %d' % [@line.category.capitalize, @line.line_number]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/new
  # GET /lines/new.json
  def new
    @budget = Budget.find(params[:budget_id])
    @line = Line.new
    @line.category = params[:category]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line }
    end
  end

  # GET /lines/1/edit
  # TODO: Might have to modify this
  def edit
    @line = Line.find(params[:id])
    @budget = @line.budget
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(params[:line])
    @line.budget_id = params[:budget_id]
    @budget = @line.budget

    respond_to do |format|
      if @line.save
        format.html { redirect_to budget_path(@budget), notice: 'Line was successfully created.' }
        format.json { render json: @line, status: :created, location: @line }
      else
        format.html { render action: "new" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lines/1
  # PUT /lines/1.json
  # TODO: Might have to modify this
  def update
    @line = Line.find(params[:id])
    @budget = @line.budget

    respond_to do |format|
      if @line.update_attributes(params[:line])
        format.html { redirect_to budget_path(@budget), notice: 'Line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line = Line.find(params[:id])
    @line.destroy

    respond_to do |format|
      format.html { redirect_to budget_path(@line.budget) }
      format.json { head :no_content }
    end
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<fieldset>

<div class="control-group">
   <%= f.label :line_number, t("activerecord.attributes.line.line_number", :default => "Line number"), :class => 'control-label' %>
  <div class="controls">
    <%= f.number_field :line_number, :class => 'number_field', :min => 100, :step => 100 %>
  </div>
</div>

<div class="control-group">
   <%= f.label :name, t("activerecord.attributes.line.name", :default => "Name"), :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<!--
<div class="control-group">
   <%= f.label :subtotal, t("activerecord.attributes.line.subtotal", :default => "Subtotal"), :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :subtotal, :class => 'text_field' %>
  </div>
</div>
-->

<div class="control-group">
   <%= f.label :category, t("activerecord.attributes.line.category", :default => "category"), :class => 'control-label' %>
  <div class="controls">
    <%= f.select :category, Line::CATEGORIES, :class => 'select' %>
  </div>
</div>

</fieldset>

<div class="form-actions">
  <button class="btn btn-primary" type="submit">Save</button> or
	<%= link_to "Cancel", @line.id ? budget_line_path(@budget, @line) : budget_path(@budget) + '/' + @line.category, :class => 'danger' %>
</div>

app/views/lines/_list.html.erb
<div class="head">
    <h2 class="pull-left"><%= category.capitalize %></h2>
    <h2 class="pull-right <%= "danger" unless @budget.category_balanced(category) %>"><%= number_to_currency(@budget.category_actual(category), :unit => "") %>/<%= number_to_currency(@budget.category_budget(category), :unit => "") %></h2>
</div>

<div class="controls buffer">
    <%= link_to "New " + category.capitalize, new_budget_line_path(@budget)+'/'+category, :class => 'btn' %>
</div>

<% if lines.empty? %>
<p>No <%= category %></p>
<% else %>
<table class="table table-striped">

    <thead>
        <th>#</th>
        <th>name</th>
        <th>budget</th>
        <th>actual</th>
        <th></th>
    </thead>

    <tbody>

        <% lines.each do |line| %>
        <tr>
            <td><%= line.line_number %></td>
            <td><%= line.name %></td>
            <td><%= number_to_currency(line.budget_total, :unit => "") %></td>
            <td><%= number_to_currency(line.actual, :unit => "") %></td>
            <td class="controls hide">
                <%= link_to "show", budget_line_path(@budget, line) %>
                <%= link_to "edit", edit_line_path(line) %>
                <%= link_to "delete", budget_line_path(@budget, line), :method => :delete, :class => 'danger', :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" -%>
            </td>
        </tr>
        <% end %>

    </tbody>

</table>
<% end %>

app/views/lines/edit.html.erb
<section class="form span7">

    <%= form_for @line, :url => line_path(@line), :html => { :class => "edit_line form-horizontal", :id => "edit_line" } do |f| -%>
        <legend>Edit Line "<%= @line.name %>" - <%= @budget.title %></legend>
        <input name="_method" type="hidden" value="put" />
        <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>

app/views/lines/new.html.erb
<section class="form span7">

    <%= form_for [@budget,@line], :url => budget_lines_path, :html => { :class => 'form-horizontal' } do |f| -%>
        <legend>New Line - <%= @budget.title %></legend>
        <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>

app/views/lines/show.html.erb
<section class="details span12">

    <table class="table table-highlight">

        <thead>

            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Category</th>
                <th>Budget</th>
                <th>Actual</th>
                <th>Excess</th>
                <th></th>
            </tr>

        </thead>

        <tbody>

            <tr>
                <td><%= @line.line_number %></td>
                <td><%= @line.name %></td>
                <td><%= @line.category.capitalize %></td>
                <td><%= number_to_currency(@line.budget_total, :unit => "") %></td>
                <td><%= number_to_currency(@line.actual, :unit => "") %></td>
                <td class="<%= "danger" unless @line.excess >= 0 %>"><%= number_to_currency(@line.excess, :unit => "") %></td>
                <td class="controls">
                    <%= link_to "Edit", edit_budget_line_path(@budget, @line) %>
                    <%= link_to "Delete", budget_line_path(@budget, @line), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'danger' %>
                </td>
            </tr>

        </tbody>

    </table>

</section>

<section class="sublines span6">

    <%= render :partial => 'sublines/list', :locals => { :sublines => @line.sublines } %>

</section>

<section class="transactions span6">

    <% unless @line.sublines.empty? %>

    <ul class="well no-list tab-content">
        <li class="tab-pane active"><h3>Select a subline to view transactions</h3></li>
        <% @line.sublines.each do |subline| %>
        <li id="subline_<%= subline.id %>" class="tab-pane">
            <%= render :partial => 'transactions/list', :locals => { 
                    :subline => subline, :transactions => subline.transactions } %>
        </li>
        <% end %>
    </ul>

    <% end %>

</section>