config/routes.rb
CloudCount2::Application.routes.draw do

  resources :audits

  resources :sessions, :only => [:new, :create, :destroy]
  match 'logout', to: 'sessions#destroy', as: :logout
  match 'login', to: 'sessions#new', as: :login

  resources :budgets do 

    resources :lines

    resources :notes

    resources :attachments

  end
  match '/budgets/:id/:category', to: 'budgets#show'

  match '/budgets/:budget_id/lines/new/:category', to: 'lines#new'
  resources :lines do
    resources :sublines
  end

  resources :sublines do
    resources :transactions
  end

  resources :users
  match 'signup', to: 'users#new', as: :signup

  root :to => 'budgets#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  before_filter :setup
  before_filter :require_login

  respond_to :html, :json

  def setup
    @subtitle = 'Transactions'
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @subline = Subline.find(params[:subline_id])
    @line = @subline.line
    @budget = @line.budget

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
    @subline = @transaction.subline
    @line = @subline.line
    @budget = @line.budget
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])
    @subline = Subline.find(params[:subline_id])
    @line = @subline.line
    @budget = @line.budget

    @transaction.subline_id = @subline.id

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to budget_line_path(@budget, @line), notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])
    @subline = @transaction.subline
    @line = @subline.line
    @budget = @line.budget

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to budget_line_path(@budget, @line), notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @line = @transaction.subline.line
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to budget_line_path(@line.budget_id, @line), notice: 'Transaction was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<fieldset>

    <div class="control-group">
       <%= f.label :name, t("activerecord.attributes.transaction.name", :default => "Name"), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
       <%= f.label :subtotal, t("activerecord.attributes.transaction.subtotal", :default => "Subtotal"), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :subtotal, :class => 'text_field' %>
      </div>
    </div>

</fieldset>

<div class="form-actions">
  <button class="btn btn-primary" type="submit">Save</button> or
	<%= link_to "Cancel", budget_line_path(@budget, @line), :class => 'danger' %>
</div>

app/views/transactions/_list.html.erb
<div class="head">
    <h3>Transactions > <%= subline.name %></h3>
</div>

<div class="controls buffer">
    <%= link_to "New Transaction", new_subline_transaction_path(subline), :class => 'btn' %>
</div>

<% if transactions.empty? %>
<p>No transactions...</p>
<% else %>
<table class="table">

    <thead>
        <th>amount</th>
        <th>for</th>
        <th>on</th>
        <th></th>
    </thead>

    <tbody>

        <% transactions.each do |transaction| %>
        <tr>
            <td><%= number_to_currency(transaction.subtotal, :unit => "") %></td>
            <td><%= transaction.name %></td>
            <td><%= transaction.created_at %></td>
            <td class="controls">
                <%= link_to "edit", edit_subline_transaction_path(subline, transaction) %>
                <%= link_to "delete", subline_transaction_path(subline, transaction), :method => :delete, :class => 'danger', :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" -%>
            </td>
        </tr>
        <% end %>

    </tbody>

</table>
<% end %>

app/views/transactions/edit.html.erb
<section class="form span7">

    <%= form_for @transaction, :url => subline_transaction_path(@subline, @transaction), :html => { :class => "edit_transaction form-horizontal", :id => "edit_transaction" } do |f| -%>
        <legend>Edit Transaction "<%= @transaction.name %>" - <%= "%d.%d" % [@line.line_number, @subline.line_number]  %> <%= @subline.name -%></legend>
        <input name="_method" type="hidden" value="put" />
        <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>

app/views/transactions/new.html.erb
<section class="form span7">

    <%= form_for @transaction, :url => subline_transactions_path, :html => { :class => 'form-horizontal' } do |f| -%>
        <legend>New Transaction - <%= "%d.%d" % [@line.line_number, @subline.line_number]  %> <%= @subline.name -%></legend>
        <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>