config/routes.rb
CloudCount2::Application.routes.draw do

  resources :audits

  resources :sessions, :only => [:new, :create, :destroy]
  match 'logout', to: 'sessions#destroy', as: :logout
  match 'login', to: 'sessions#new', as: :login

  resources :budgets do 

    resources :lines

    resources :notes

    resources :attachments

  end
  match '/budgets/:id/:category', to: 'budgets#show'

  match '/budgets/:budget_id/lines/new/:category', to: 'lines#new'
  resources :lines do
    resources :sublines
  end

  resources :sublines do
    resources :transactions
  end

  resources :users
  match 'signup', to: 'users#new', as: :signup

  root :to => 'budgets#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudCount2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- top bar -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">

      <!-- title -->
      <a class="brand" href="/">Cloud Count</a>

      <!-- nav -->
      <ul class="nav">
        <li><%= link_to "Budgets", budgets_path %></li>
        <!-- search
        <li>
          <form class="navbar-search pull-left" action="">
            <input type="text" class="search-query span2" placeholder="Search">
          </form>
        </li>-->
      </ul>

      <!-- settings -->
      <ul class="nav pull-right">
        <% if @current_user %>
          <li class="<%= "active" if @subtitle == 'Audit' %>"><%= link_to "Audit", audits_path() %></li>
          <li><%= link_to "Users", users_path() %></li>
          <li><a href="/settings">logged in as <%= @current_user.display_name if @current_user %></a></li>
          <li><a href="/logout">Logout</a></li>
        <% else %>
          <li><%= link_to 'Login', login_path, class: 'login_link' %></li><li><%= link_to 'Signup', signup_path %></li>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<!-- content -->
<div id="main" role="main" class="container">

<div class="row">

<% unless @budget.nil? || @budget.id.nil? %>

<header class="span12">

    <h1 class="title pull-left">
      <%= link_to @budget.title, budget_path(@budget), :title => '"' + @budget.title + '" Home' %>
      <% if @subtitle %>
      <small><%= @subtitle %></small>
      <% end %>
    </h1>

    <ul class="nav nav-pills pull-right">

      <li class="<%= "active" if @subtitle == 'Budget' %>"><%= link_to "Budget", budget_path(@budget) %></li>

      <li class="<%= "active" if @subtitle == 'Notes' %>"><%= link_to "Notes", budget_notes_path(@budget) %></li>

      <li class="<%= "active" if @subtitle == 'Attachments' %>"><%= link_to "Attachments", budget_attachments_path(@budget) %></li>

    </ul>

</header>

<% end %>

<% if flash[:notice] || flash[:error] %>
  <div id="status_bar" class="span12">
    <%= render :partial => 'shared/flash_bar' %>
  </div>
<% end %>

<%= yield %>

</div>

</div>

</body>
</html>