config/routes.rb
CloudCount2::Application.routes.draw do

  resources :audits

  resources :sessions, :only => [:new, :create, :destroy]
  match 'logout', to: 'sessions#destroy', as: :logout
  match 'login', to: 'sessions#new', as: :login

  resources :budgets do 

    resources :lines

    resources :notes

    resources :attachments

  end
  match '/budgets/:id/:category', to: 'budgets#show'

  match '/budgets/:budget_id/lines/new/:category', to: 'lines#new'
  resources :lines do
    resources :sublines
  end

  resources :sublines do
    resources :transactions
  end

  resources :users
  match 'signup', to: 'users#new', as: :signup

  root :to => 'budgets#index'

end

app/models/subline.rb
class Subline < ActiveRecord::Base

    belongs_to :line

    has_many :transactions, :order => 'created_at DESC', :dependent => :destroy

    audited

    def actual
        if @actual_total.nil?
            @actual_total = self.transactions.reduce(0) do |sum, transaction|
                sum + transaction.subtotal
            end
        end
        @actual_total
    end

end

app/controllers/sublines_controller.rb
class SublinesController < ApplicationController
  
  before_filter :setup
  before_filter :require_login

  respond_to :html, :json
  
  def setup
    @subtitle = 'Sublines'
  end

  # GET /sublines
  # GET /sublines.json
  def index
    @line = Line.includes(:sublines).find(params[:line_id])
    @budget = @line.budget
    @sublines = @line.sublines
    @subline = Subline.new

    respond_with(@budget, @lines)
  end

  # GET /sublines/new
  # GET /sublines/new.json
  def new
    @line = Line.find(params[:line_id])
    @budget = @line.budget
    @subline = Subline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subline }
    end
  end

  # GET /sublines/1/edit
  def edit
    @subline = Subline.find(params[:id])
    @line = @subline.line
    @budget = @line.budget
  end

  # POST /sublines
  # POST /sublines.json
  def create
    @subline = Subline.new(params[:subline])
    @subline.line_id = params[:line_id]
    @line = @subline.line
    @budget = @subline.line.budget

    respond_to do |format|
      if @subline.save
        format.html { redirect_to budget_line_path(@budget, @line), notice: 'Subline was successfully created.' }
        format.json { render json: @subline, status: :created, location: @subline }
      else
        format.html { render action: "new" }
        format.json { render json: @subline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sublines/1
  # PUT /sublines/1.json
  def update
    @subline = Subline.find(params[:id])
    @line = @subline.line
    @budget = @line.budget

    respond_to do |format|
      if @subline.update_attributes(params[:subline])
        format.html { redirect_to budget_line_path(@budget, @line), notice: 'Subline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sublines/1
  # DELETE /sublines/1.json
  def destroy
    @subline = Subline.find(params[:id])
    @subline.destroy

    respond_to do |format|
      format.html { redirect_to budget_line_path(@subline.line.budget, @subline.line) }
      format.json { head :no_content }
    end
  end
end

app/helpers/sublines_helper.rb
module SublinesHelper
end

app/views/sublines/_form.html.erb
<fieldset>

  <div class="control-group">
     <%= f.label :line_number, t("activerecord.attributes.subline.line_number", :default => "Line Number"), :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :line_number, :class => 'number_field', :min => 1 %>
    </div>
  </div>

  <div class="control-group">
     <%= f.label :name, t("activerecord.attributes.subline.name", :default => "Name"), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
     <%= f.label :subtotal, t("activerecord.attributes.subline.subtotal", :default => "Subtotal"), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtotal, :class => 'text_field' %>
    </div>
  </div>

</fieldset>

<div class="form-actions">
  <button class="btn btn-primary" type="submit">Save</button> or
	<%= link_to "Cancel", budget_line_path(@budget, @line), :class => 'danger' %>
</div>

app/views/sublines/_list.html.erb
<div class="head">
    <h2>Sublines</h2>
</div>

<div class="controls buffer">
    <%= link_to "New Subline", new_line_subline_path(@line), :class => 'btn' %>
</div>

<% if sublines.empty? %>
<p>No sublines...</p>
<% else %>
<table class="table table-striped">

    <thead>
        <th>#</th>
        <th>name</th>
        <th>budget</th>
        <th>actual</th>
        <th></th>
    </thead>

    <tbody>

        <% sublines.each do |subline| %>
        <tr>
            <td><%= @line.line_number %>.<%= subline.line_number %></td>
            <td><%= subline.name %></td>
            <td><%= number_to_currency(subline.subtotal, :unit => "") %></td>
            <td><%= number_to_currency(subline.actual, :unit => "") %></td>
            <td class="controls">
                <a href="#subline_<%= subline.id %>" data-toggle="tab">transactions</a>
                <%= link_to "edit", edit_subline_path(subline) %>
                <%= link_to "delete", line_subline_path(@line, subline), :method => :delete, :class => 'danger', :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" -%>
            </td>
        </tr>
        <% end %>

    </tbody>

</table>
<% end %>

app/views/sublines/edit.html.erb
<section class="form span7">

    <%= form_for @subline, :url => line_subline_path(@line, @subline), :html => { :class => "edit_subline form-horizontal", :id => "edit_subline" } do |f| -%>
      <input name="_method" type="hidden" value="put" />
      <legend>Edit Subline "<%= @subline.name %>" - <%= @line.line_number %> <%= @line.name %></legend>
      <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>

app/views/sublines/index.html.erb
<h1>Sublines</h1>
<table class="zebra-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.subline.line_id", :default => t("activerecord.labels.line_id", :default => "Line_id")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sublines.each do |subline| -%>
   <tr>
    <td><%= subline.id %></td>
        <td><%= link_to subline.line_id, subline_path(subline) %>
    </td>
        <td><%= subline.created_at %></td>
    <td>
      <%= link_to "Show", subline_path(subline) %>
      <%= link_to "Edit", edit_subline_path(subline) %>
      <%= link_to "Destroy", line_sublines_path(@line), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_line_subline_path, :class => 'btn primary' %>

app/views/sublines/new.html.erb
<section class="form span7">

    <%= form_for [@line,@subline], :url => line_sublines_path, :html => { :class => 'form-horizontal' } do |f| -%>
        <legend>New Subline - <%= @line.line_number %> <%= @line.name %></legend>
        <%= render :partial => "form", :locals => {:f => f} %>
    <% end -%>

</section>

app/views/sublines/show.html.erb
<label class="label"><%= t("activerecord.attributes.subline.line_id", :default => t("activerecord.labels.line_id", :default => "Line")) %>:</label>
<p><%= @subline.line_id %></p>

<label class="label"><%= t("activerecord.attributes.subline.line_number", :default => t("activerecord.labels.line_number", :default => "Line number")) %>:</label>
<p><%= @subline.line_number %></p>

<label class="label"><%= t("activerecord.attributes.subline.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</label>
<p><%= @subline.name %></p>

<label class="label"><%= t("activerecord.attributes.subline.subtotal", :default => t("activerecord.labels.subtotal", :default => "Subtotal")) %>:</label>
<p><%= @subline.subtotal %></p>

<label class="label"><%= t("activerecord.attributes.subline.category", :default => t("activerecord.labels.category", :default => "category")) %>:</label>
<p><%= @subline.category %></p>

<label class="label"><%= t("activerecord.attributes.subline.order", :default => t("activerecord.labels.order", :default => "Order")) %>:</label>
<p><%= @subline.order %></p>
<div class="actions">
<%= link_to "Back", line_sublines_path, :class => 'btn primary'  %>
<%= link_to "Edit", edit_subline_path(@subline), :class => 'btn primary' %>
<%= link_to "Delete", subline_path(@subline), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn primary' %>
</div>